# Generated by Django 4.1.1 on 2022-09-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_shifttable_alter_personalshift_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastershift',
            name='shift_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shifttable'),
        ),
    ]
