# Generated by Django 4.1.1 on 2022-09-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_monthlyworker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyworker',
            old_name='month',
            new_name='table',
        ),
    ]
