# Generated by Django 4.1.1 on 2022-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_delete_monthlyworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalshift',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
